# Generated by Django 3.2.6 on 2022-02-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=50)),
                ('pages', models.PositiveIntegerField()),
                ('publication_year', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('available', models.BooleanField()),
                ('available_numbers', models.PositiveIntegerField(default=3)),
                ('book_imgs', models.ImageField(default='books_cover/Question-Mark-PNG.webp', upload_to='books_cover')),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='books_files')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.category')),
                ('lent_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
