# Generated by Django 3.2.6 on 2022-02-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='lent_by',
        ),
        migrations.AddField(
            model_name='book',
            name='lent_by',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
