# Generated by Django 3.2.6 on 2022-02-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220226_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_imgs',
            field=models.ImageField(blank=True, default='books_cover/Question-Mark-PNG.webp', null=True, upload_to='books_cover'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
