# Generated by Django 3.2.6 on 2022-02-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20220227_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_imgs',
            field=models.ImageField(blank=True, default='books_cover/unknown-book.jpeg', null=True, upload_to='books_cover'),
        ),
    ]
