# Generated by Django 3.2.6 on 2022-02-13 07:28

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_code', models.CharField(max_length=10)),
                ('birth_date', models.DateField()),
                ('phone_no', models.CharField(max_length=11)),
                ('invitation_code', models.CharField(default=account.models.generate_invitation_code, editable=False, max_length=8, unique=True)),
                ('invited_people', models.PositiveIntegerField(default=0)),
                ('dedicated_book', models.PositiveIntegerField(default=0)),
                ('start_subs', models.DateField(blank=True, null=True)),
                ('end_subs', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, upload_to='users_profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
