# Generated by Django 3.2.6 on 2022-02-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='national_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
