# Generated by Django 3.2.6 on 2022-02-13 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_userinformations_national_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='users_profile_pics'),
        ),
    ]
