# Generated by Django 3.2.6 on 2022-02-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userinformations_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/users_profile_pics/empty-profile-picture-profile-anonymous.png/', null=True, upload_to='users_profile_pics'),
        ),
    ]
