# Generated by Django 3.2.6 on 2022-02-17 10:07

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userinformations_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='invitation_code',
            field=models.CharField(default=account.models.generate_invitation_code, max_length=8, unique=True),
        ),
    ]
