# Generated by Django 3.2.6 on 2022-02-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_userinformations_invitation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='subscription_type',
            field=models.CharField(blank=True, choices=[('bronze', 'برنزی'), ('silver', 'نقره\u200cای'), ('golden', 'طلایی')], max_length=10, null=True),
        ),
    ]
