# Generated by Django 3.2.6 on 2022-02-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_userinformations_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='current_invtd_ppl',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
