# Generated by Django 3.2.6 on 2022-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userinformations_current_invtd_ppl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformations',
            name='end_subs',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinformations',
            name='start_subs',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
