# Generated by Django 3.2.6 on 2022-02-22 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220219_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavoritebook',
            name='title',
        ),
    ]
