# Generated by Django 3.2.6 on 2022-02-26 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20220226_1646'),
        ('account', '0012_auto_20220226_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritebook',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
