# Generated by Django 3.2.6 on 2022-03-10 14:28

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_userfavoritebook_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformations',
            name='test_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
