# Generated by Django 3.2.6 on 2022-03-13 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0016_auto_20220310_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('subscription_type', models.CharField(blank=True, choices=[('برنزی (یک ماهه)', 'bronze(1 months)'), ('نقره\u200cای (سه ماهه)', 'silver(3 months)'), ('طلایی (یک ساله)', 'golden(12 months)')], max_length=20, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
