# Generated by Django 3.2.6 on 2022-03-26 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0005_remove_book_price'),
        ('account', '0018_alter_subscriptionrecord_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', django_jalali.db.models.jDateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('librarian', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_admin', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='library_membr', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
