# Generated by Django 3.2.6 on 2022-03-26 13:45

import datetime
from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_alter_lendbook_loan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendbook',
            name='loan_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 3, 26)),
        ),
    ]
