# Generated by Django 4.0.3 on 2022-03-26 16:45

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_alter_lendbook_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendbook',
            name='due_date',
            field=django_jalali.db.models.jDateField(default='2020-10-10'),
            preserve_default=False,
        ),
    ]
