# Generated by Django 4.0.3 on 2022-03-27 07:08

import datetime
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_lendbook_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformations',
            name='does_lend',
        ),
        migrations.RemoveField(
            model_name='userinformations',
            name='lend_in',
        ),
        migrations.AddField(
            model_name='userinformations',
            name='allowed_to_lend',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userinformations',
            name='lent_num',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lendbook',
            name='loan_date',
            field=django_jalali.db.models.jDateField(default=datetime.date(2022, 3, 27)),
        ),
    ]
