# Generated by Django 4.0.3 on 2022-03-27 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0023_remove_userinformations_does_lend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendbook',
            name='member',
            field=models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='library_member', to=settings.AUTH_USER_MODEL),
        ),
    ]
